"""empty message

Revision ID: 54ef4cfedc30
Revises: 
Create Date: 2019-11-22 22:24:23.421405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ef4cfedc30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('data_agendamento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'data_agendamento')
    # ### end Alembic commands ###
