"""empty message

Revision ID: 89f5463e96bb
Revises: 
Create Date: 2019-07-24 18:38:17.925165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f5463e96bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('favorito', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'favorito')
    # ### end Alembic commands ###
