"""empty message

Revision ID: db1c2c1a82f3
Revises: 89f5463e96bb
Create Date: 2019-07-24 19:25:38.998463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1c2c1a82f3'
down_revision = '89f5463e96bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'favorito')
    op.add_column('produtos', sa.Column('favoritar', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'favoritar')
    op.add_column('pedidos', sa.Column('favorito', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
